version: '3.9'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: carshowroom
    ports:
      - "5435:5432"