datasource:
 url: jdbc:postgresql://localhost:5435/carshowroom
 password: root
 user: root
 driver: org.postgresql.Driver
liquibase:
 changelog: classpath:db/changelog/db.changelog-master.yaml
hibernate:
 format_sql: true
 use_sql_comments: true
 show_sql: true
